repos:
  - repo: local
    hooks:
      - id: export-conda-env
        name: Export Conda env to environment.yml
        entry: scripts/export_conda_env.sh
        language: script
        pass_filenames: false
        always_run: true